set_property SRC_FILE_INFO {cfile:F:/stu70048/Desktop/vivado-tutorial-master/vivado_tutorial.srcs/constrs_1/new/test_pin.xdc rfile:F:/stu70048/Desktop/vivado-tutorial-master/vivado_tutorial.srcs/constrs_1/new/test_pin.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J1 [get_ports led]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H4 [get_ports sys_clk]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C3 [get_ports {key[0]}]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M4 [get_ports {key[1]}]
