@echo off
REM ****************************************************************************
REM Vivado (TM) v2022.1.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sun Aug 07 22:00:59 +0800 2022
REM SW Build 3557992 on Fri Jun  3 09:58:00 MDT 2022
REM
REM IP Build 3556342 on Fri Jun  3 19:31:36 MDT 2022
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim test2_behav -key {Behavioral:sim_1:Functional:test2} -tclbatch test2.tcl -protoinst "protoinst_files/test2_design.protoinst" -log simulate.log"
call xsim  test2_behav -key {Behavioral:sim_1:Functional:test2} -tclbatch test2.tcl -protoinst "protoinst_files/test2_design.protoinst" -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
